#!/usr/bin/env node
/**
 * Build-time config generator for the sample app.
 *
 *   node example/scripts/gen-env.mjs
 *
 * Reads `example/.env` and writes `example/src/env.generated.ts` exporting
 * **exactly three** names:
 *
 *   UQPAY_ENVIRONMENT · UQPAY_CLIENT_ID · UQPAY_MERCHANT_BACKEND_URL
 *
 * The allow-list is the point. `example/.env` also holds the merchant API key
 * for the reference backend; that variable is not read here, is not written
 * here, and a test fails if any file under `example/src` so much as names it
 * (AC RN-SEC3, KICKOFF §7). There is no `react-native-config` dependency:
 * this is 60 lines of Node and one generated file.
 *
 * `env.generated.ts` is gitignored. Run this script after editing `.env`,
 * before `yarn example start` / `ios` / `android`.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { loadEnvFile, makeReader } from '../backend/lib/env.mjs';

/** The only variables the app is allowed to see. */
export const APP_VARIABLES = /** @type {const} */ ([
  'UQPAY_ENVIRONMENT',
  'UQPAY_CLIENT_ID',
  'UQPAY_MERCHANT_BACKEND_URL',
]);

const DEFAULTS = {
  UQPAY_ENVIRONMENT: 'sandbox',
  UQPAY_CLIENT_ID: '',
  UQPAY_MERCHANT_BACKEND_URL: 'http://localhost:8787',
};

/**
 * Builds the generated TypeScript source.
 *
 * @param {Record<string, string>} values
 * @returns {string}
 */
export function renderEnvModule(values) {
  const lines = [
    // Generated output is not hand-written source: exempt it from lint and
    // formatting rather than teaching the generator to emit Prettier's quote style.
    '/* eslint-disable prettier/prettier -- generated file, see example/scripts/gen-env.mjs */',
    '// GENERATED by example/scripts/gen-env.mjs — do not edit, do not commit.',
    '// Regenerate with: node example/scripts/gen-env.mjs',
    '//',
    '// Only the three non-secret variables the app is allowed to read appear here.',
    '// The merchant API key stays in example/.env and is read by',
    '// example/backend/ alone (AC RN-SEC3).',
    '',
  ];
  for (const name of APP_VARIABLES) {
    const value = values[name] ?? DEFAULTS[name];
    // Annotated `: string` on purpose: without it TypeScript infers a
    // literal type and every comparison against another value becomes a
    // 'no overlap' error in the app.
    lines.push(`export const ${name}: string = ${JSON.stringify(value)};`);
  }
  lines.push('');
  return lines.join('\n');
}

export function generate({ envFile, outFile } = {}) {
  const here = dirname(fileURLToPath(import.meta.url));
  const env = envFile ?? resolve(here, '..', '.env');
  const out = outFile ?? resolve(here, '..', 'src', 'env.generated.ts');

  const { values, loaded, reason } = loadEnvFile(env);
  const read = makeReader(values);

  /** @type {Record<string, string>} */
  const picked = {};
  for (const name of APP_VARIABLES) picked[name] = read(name) ?? DEFAULTS[name];

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, renderEnvModule(picked), 'utf8');

  return { out, loaded, reason, picked };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const { out, loaded, reason, picked } = generate();
  if (!loaded) {
    console.warn(`example/.env ${reason ?? 'not loaded'} — writing defaults.`);
    console.warn('Copy example/.env.template to example/.env and fill it in.');
  }
  // Only the environment and the backend URL are printed; the client id is not
  // a secret but there is no reason to put it in a terminal scrollback either.
  console.log(
    `wrote ${out} (UQPAY_ENVIRONMENT=${picked.UQPAY_ENVIRONMENT}, ` +
      `UQPAY_MERCHANT_BACKEND_URL=${picked.UQPAY_MERCHANT_BACKEND_URL}, ` +
      `UQPAY_CLIENT_ID=${picked.UQPAY_CLIENT_ID === '' ? '<unset>' : 'set'})`
  );
}
