/**
 * Renderers shared by `errors:generate`, `errors:sync` and the Jest drift test,
 * so "generated" and "checked" can never be produced by different code
 * (AC RN-DOC4, RN-PAR3).
 */
import { ERROR_TABLE, type ErrorTableRow } from '../src/errors/table.ts';
import {
  SCENARIOS,
  type Scenario,
} from '../src/__tests__/fixtures/scenarios.ts';

/** Where the generated artefacts live, relative to the repository root. */
export const OUTPUT_PATHS = {
  errorCodesDoc: 'ERROR_CODES.md',
  errorTableJson: 'src/errors/error-table.json',
  iosFixtureDir: 'ios/Tests/Fixtures',
  androidFixtureDir: 'android/src/test/resources',
  errorTableFixture: 'error-table.json',
  scenariosFixture: 'scenarios.json',
} as const;

const GENERATED_BY =
  '<!-- Generated by `yarn errors:generate` from src/errors/table.ts. Do not edit by hand. -->';

function yesNo(value: boolean): string {
  return value ? 'yes' : 'no';
}

/** Render `ERROR_CODES.md` (AC RN-DOC4). */
export function renderErrorCodesDoc(
  rows: ReadonlyArray<ErrorTableRow> = ERROR_TABLE
): string {
  const header = [
    '| Code | Meaning | Retryable | Outcome unknown | What you should do | What the customer is told | Platforms |',
    '|---|---|---|---|---|---|---|',
  ];
  const body = rows.map(
    (row) =>
      `| \`${row.code}\` | ${row.meaning} | ${yesNo(row.isRetryable)} | ${yesNo(
        row.isOutcomeUnknown
      )} | ${row.developerHint} | ${row.userMessage} | ${row.platforms.join(', ')} |`
  );

  return [
    '# UQPAY React Native — error codes',
    '',
    GENERATED_BY,
    '',
    'Every `UqpayError` carries one of these codes. The set is produced by exactly one mapper',
    'per platform, so the same server condition yields the same code on iOS and Android.',
    'A code that is not in this table is passed through untouched with the native value in',
    '`error.raw`, and `isUnknownErrorCode(code)` returns `true`.',
    '',
    '**Outcome unknown** means the payment may still have succeeded: never show the customer a',
    'failure, never charge again, and reconcile from your server.',
    '',
    ...header,
    ...body,
    '',
    '## Reading the columns',
    '',
    '- **Retryable** — retrying the *same* action can plausibly succeed. A decline is not',
    '  retryable; a transport failure is.',
    '- **Outcome unknown** — the device cannot tell whether the money moved. Always reconcile.',
    '- **What the customer is told** — the exact `error.userMessage`. It is safe to display as-is',
    '  and contains no jargon, no stack trace and no platform name.',
    '',
  ].join('\n');
}

/** The machine-readable table the Swift and Kotlin test suites read. */
export function renderErrorTableJson(
  rows: ReadonlyArray<ErrorTableRow> = ERROR_TABLE
): string {
  return `${JSON.stringify({ version: 1, generatedFrom: 'src/errors/table.ts', rows }, null, 2)}\n`;
}

/** The shared RN-TEST3 scenario fixtures, for the native suites (AC RN-PAR1). */
export function renderScenariosJson(
  scenarios: ReadonlyArray<Scenario> = SCENARIOS
): string {
  return `${JSON.stringify(
    {
      version: 1,
      generatedFrom: 'src/__tests__/fixtures/scenarios.ts',
      scenarios,
    },
    null,
    2
  )}\n`;
}
