#!/usr/bin/env node
/**
 * Build-time config generator for the Expo sample app.
 *
 *   node example-expo/scripts/gen-env.mjs
 *
 * Reads `example-expo/.env` and writes `example-expo/src/env.generated.ts`
 * exporting **exactly three** names:
 *
 *   UQPAY_ENVIRONMENT · UQPAY_CLIENT_ID · UQPAY_MERCHANT_BACKEND_URL
 *
 * Same approach, same allow-list and same three variables as the bare app's
 * `example/scripts/gen-env.mjs`. The merchant API key is NOT read here, is NOT
 * written here, and a test fails if any file under `example-expo/src` or
 * `example-expo/scripts` so much as names it (AC RN-SEC3, D7, KICKOFF §7).
 *
 * The `.env` parser is inlined rather than imported from `example/backend/`:
 * this is a separate Yarn workspace and must not reach across into another one
 * (`nmHoistingLimits: workspaces`). The two copies are small and deliberately
 * identical in behaviour.
 *
 * `env.generated.ts` is gitignored. Run this after editing `.env`, before
 * `npx expo prebuild` / `npx expo run:ios` / `run:android`. The `prestart` /
 * `preios` / `preandroid` / `preprebuild` scripts do it for you.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

/** The only variables the app is allowed to see. */
export const APP_VARIABLES = /** @type {const} */ ([
  'UQPAY_ENVIRONMENT',
  'UQPAY_CLIENT_ID',
  'UQPAY_MERCHANT_BACKEND_URL',
]);

const DEFAULTS = {
  UQPAY_ENVIRONMENT: 'sandbox',
  UQPAY_CLIENT_ID: '',
  UQPAY_MERCHANT_BACKEND_URL: 'http://localhost:8787',
};

/**
 * Parses `KEY=value` lines. Supports `export `, `#` comments, quoted values
 * and a trailing ` # comment` on an unquoted value. No interpolation, no
 * multi-line values, no dependency.
 *
 * @param {string} text
 * @returns {Record<string, string>}
 */
export function parseEnv(text) {
  /** @type {Record<string, string>} */
  const out = {};
  if (typeof text !== 'string') return out;

  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#')) continue;

    const withoutExport = line.startsWith('export ')
      ? line.slice('export '.length).trim()
      : line;

    const eq = withoutExport.indexOf('=');
    if (eq <= 0) continue;

    const key = withoutExport.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;

    let value = withoutExport.slice(eq + 1).trim();
    const quote = value[0];
    if ((quote === '"' || quote === "'") && value.endsWith(quote) && value.length >= 2) {
      value = value.slice(1, -1);
    } else {
      const hash = value.indexOf(' #');
      if (hash >= 0) value = value.slice(0, hash).trim();
    }

    out[key] = value;
  }
  return out;
}

/**
 * A missing `.env` is not an error: the app starts and the Home screen
 * explains what to fill in.
 *
 * @param {string} filePath
 * @returns {{ values: Record<string, string>, loaded: boolean, reason?: string }}
 */
export function loadEnvFile(filePath) {
  let text;
  try {
    text = readFileSync(filePath, 'utf8');
  } catch (err) {
    const code = /** @type {{ code?: string }} */ (err)?.code;
    return {
      values: {},
      loaded: false,
      reason: code === 'ENOENT' ? 'file not found' : `unreadable (${code ?? 'error'})`,
    };
  }
  return { values: parseEnv(text), loaded: true };
}

/**
 * The real process environment wins over the file, so CI can override without
 * writing a `.env`.
 *
 * @param {Record<string, string>} fileValues
 * @param {Record<string, string | undefined>} [processEnv]
 * @returns {(name: string) => string | undefined}
 */
export function makeReader(fileValues, processEnv = process.env) {
  return (name) => {
    const fromProcess = processEnv[name];
    const raw = fromProcess !== undefined && fromProcess !== '' ? fromProcess : fileValues[name];
    if (raw === undefined) return undefined;
    const trimmed = String(raw).trim();
    return trimmed === '' ? undefined : trimmed;
  };
}

/**
 * Builds the generated TypeScript source.
 *
 * @param {Record<string, string>} values
 * @returns {string}
 */
export function renderEnvModule(values) {
  const lines = [
    // Generated output is not hand-written source: exempt it from lint and
    // formatting rather than teaching the generator Prettier's quote style.
    '/* eslint-disable prettier/prettier -- generated file, see example-expo/scripts/gen-env.mjs */',
    '// GENERATED by example-expo/scripts/gen-env.mjs — do not edit, do not commit.',
    '// Regenerate with: node example-expo/scripts/gen-env.mjs',
    '//',
    '// Only the three non-secret variables the app is allowed to read appear here.',
    '// The merchant API key stays in the BACKEND\'s .env (example/.env) and is read',
    '// by example/backend/ alone (AC RN-SEC3).',
    '',
  ];
  for (const name of APP_VARIABLES) {
    const value = values[name] ?? DEFAULTS[name];
    // Annotated `: string` on purpose: without it TypeScript infers a literal
    // type and every comparison becomes a 'no overlap' error in the app.
    lines.push(`export const ${name}: string = ${JSON.stringify(value)};`);
  }
  lines.push('');
  return lines.join('\n');
}

export function generate({ envFile, outFile } = {}) {
  const here = dirname(fileURLToPath(import.meta.url));
  const env = envFile ?? resolve(here, '..', '.env');
  const out = outFile ?? resolve(here, '..', 'src', 'env.generated.ts');

  const { values, loaded, reason } = loadEnvFile(env);
  const read = makeReader(values);

  /** @type {Record<string, string>} */
  const picked = {};
  for (const name of APP_VARIABLES) picked[name] = read(name) ?? DEFAULTS[name];

  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, renderEnvModule(picked), 'utf8');

  return { out, loaded, reason, picked };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url))) {
  const { out, loaded, reason, picked } = generate();
  if (!loaded) {
    console.warn(`example-expo/.env ${reason ?? 'not loaded'} — writing defaults.`);
    console.warn('Copy example-expo/.env.template to example-expo/.env and fill it in.');
  }
  // Only the environment and the backend URL are printed; the client id is not
  // a secret but there is no reason to put it in a terminal scrollback either.
  console.log(
    `wrote ${out} (UQPAY_ENVIRONMENT=${picked.UQPAY_ENVIRONMENT}, ` +
      `UQPAY_MERCHANT_BACKEND_URL=${picked.UQPAY_MERCHANT_BACKEND_URL}, ` +
      `UQPAY_CLIENT_ID=${picked.UQPAY_CLIENT_ID === '' ? '<unset>' : 'set'})`
  );
}
